name       : kdeplasma-addons
version    : 5.20.4
release    : 61
source     :
    - https://cdn.download.kde.org/stable/plasma/5.20.4/kdeplasma-addons-5.20.4.tar.xz : 44768c7fb00386bc4f005c773bca59d8acc354f8a3f43efa6565cefc74d490d7
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
libsplit   : no
summary    : Addons for KDE Plasma
description: |
    Addons for KDE Plasma.
builddeps  :
    - pkgconfig(libKActivities)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - extra-cmake-modules
    - karchive-devel
    - kcmutils-devel
    - kdeclarative-devel
    - kholidays-devel
    - knewstuff-devel
    - knotifications-devel
    - krunner-devel
    - kunitconversion-devel
    - kross-devel
    - kwindowsystem-devel
    - libksysguard-devel
    - plasma-workspace-devel
    - purpose-devel
    - sonnet-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-diskquota.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache

    # Remove locale data for removed applet
    rm $installdir/usr/share/locale/*/LC_MESSAGES/plasma_applet_org.kde.plasma.diskquota.mo
