name       : kdeplasma-addons
version    : 5.11.0
release    : 6
source     :
    - https://download.kde.org/stable/plasma/5.11.0/kdeplasma-addons-5.11.0.tar.xz : d4ee021086d77794a20c8a08238bc83e46ca1a2c4126b5bd32b0e43cfb7f0dda
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
summary    : Addons for KDE Plasma
description: |
    Addons for KDE Plasma.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libKActivities)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - extra-cmake-modules
    - kcmutils-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdelibs4support-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - krunner-devel
    - kservice-devel
    - kunitconversion-devel
    - kross-devel
    - libksysguard-devel
    - plasma-framework-devel
    - plasma-workspace-devel
setup      : |
    mkdir build && pushd build
    %cmake ..
build      : |
    pushd build
    %make
install    : |
    pushd build
    %make_install
    cd $installdir; qml_cache
