name       : kdeplasma-addons
version    : 5.24.2
release    : 79
source     :
    - https://cdn.download.kde.org/stable/plasma/5.24.2/kdeplasma-addons-5.24.2.tar.xz : 13e62f9091f26eeff7d4bf4a51569c2af561dd051d1c1d94b98071a7465d6cf3
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.kde.core
summary    : Addons for KDE Plasma
description: |
    Addons for KDE Plasma.
optimize   : lto
libsplit   : no
builddeps  :
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - kactivities-devel
    - karchive-devel
    - kcmutils-devel
    - kdeclarative-devel
    - kholidays-devel
    - kio-devel
    - knewstuff-devel
    - knotifications-devel
    - krunner-devel
    - kunitconversion-devel
    - libksysguard-devel
    - purpose-devel
    - sonnet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
