name       : kdeplasma-addons
version    : 5.13.3
release    : 21
source     :
    - https://cdn.download.kde.org/stable/plasma/5.13.3/kdeplasma-addons-5.13.3.tar.xz : 831a9e5a127a169eef458d5328145cad5ecf6f28f65d8d6e1ce008618a1b0d15
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
libsplit   : no
summary    : Addons for KDE Plasma
description: |
    Addons for KDE Plasma.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libKActivities)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - extra-cmake-modules
    - karchive-devel
    - kcmutils-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdeclarative-devel
    - kholidays-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - knotifications-devel
    - krunner-devel
    - kservice-devel
    - kunitconversion-devel
    - kross-devel
    - libksysguard-devel
    - plasma-framework-devel
    - plasma-workspace-devel
    - purpose-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
