name       : kdeplasma-addons
version    : 5.22.2
release    : 70
source     :
    - https://cdn.download.kde.org/stable/plasma/5.22.2.1/kdeplasma-addons-5.22.2.1.tar.xz : db876a5bcdfd57f96ba219399baa1d1eae49ed79e009010a1fdbbf256ea20023
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.kde.core
summary    : Addons for KDE Plasma
description: |
    Addons for KDE Plasma.
optimize   : lto
libsplit   : no
builddeps  :
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - kactivities-devel
    - karchive-devel
    - kcmutils-devel
    - kdeclarative-devel
    - kholidays-devel
    - knewstuff-devel
    - knotifications-devel
    - krunner-devel
    - kunitconversion-devel
    - kross-devel
    - libksysguard-devel
    - purpose-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-diskquota.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache

    # Remove locale data for removed applet
    rm $installdir/usr/share/locale/*/LC_MESSAGES/plasma_applet_org.kde.plasma.diskquota.mo
