name       : kdeplasma-addons
version    : 5.14.3
release    : 29
source     :
    - https://cdn.download.kde.org/stable/plasma/5.14.3/kdeplasma-addons-5.14.3.tar.xz : 95544323d293de8b73cadf15233df05f5e9b54e5ef884099f9429cea1d2788e7
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
libsplit   : no
summary    : Addons for KDE Plasma
description: |
    Addons for KDE Plasma.
builddeps  :
    - pkgconfig(libKActivities)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - extra-cmake-modules
    - karchive-devel
    - kcmutils-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdeclarative-devel
    - kholidays-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - knotifications-devel
    - krunner-devel
    - kservice-devel
    - kunitconversion-devel
    - kross-devel
    - libksysguard-devel
    - plasma-framework-devel
    - plasma-workspace-devel
    - purpose-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-diskquota.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache

    # Remove locale data for removed applet
    rm $installdir/usr/share/locale/*/LC_MESSAGES/plasma_applet_org.kde.plasma.diskquota.mo
