name       : kdeplasma-addons
version    : 5.12.5
release    : 17
source     :
    - https://cdn.download.kde.org/stable/plasma/5.12.5/kdeplasma-addons-5.12.5.tar.xz : 5af0b5e5e47a18abbb8c8e563598d3e9b99db57617faa6d7bf668188afd2698c
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
libsplit   : no
summary    : Addons for KDE Plasma
description: |
    Addons for KDE Plasma.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libKActivities)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - extra-cmake-modules
    - kcmutils-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdelibs4support-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - krunner-devel
    - kservice-devel
    - kunitconversion-devel
    - kross-devel
    - libksysguard-devel
    - plasma-framework-devel
    - plasma-workspace-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
