name       : kdeplasma-addons
version    : 5.24.5
release    : 82
source     :
    - https://cdn.download.kde.org/stable/plasma/5.24.5/kdeplasma-addons-5.24.5.tar.xz : 3db52bc3c594d92deea3cfcb3112b4fa6ce328b7481acaa79187dab274e5e80e
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.kde.core
summary    : Addons for KDE Plasma
description: |
    Addons for KDE Plasma.
optimize   : lto
libsplit   : no
builddeps  :
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - kactivities-devel
    - karchive-devel
    - kcmutils-devel
    - kdeclarative-devel
    - kholidays-devel
    - kio-devel
    - knewstuff-devel
    - knotifications-devel
    - krunner-devel
    - kunitconversion-devel
    - libksysguard-devel
    - purpose-devel
    - sonnet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
