name       : kdeplasma-addons
version    : 5.15.5
release    : 35
source     :
    - https://download.kde.org/stable/plasma/5.15.5/kdeplasma-addons-5.15.5.tar.xz : 1e11158f636e1d4bb25bbe4bb2f2fca37728c6aae07340ca6c2c1ec9e882ece3
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
libsplit   : no
summary    : Addons for KDE Plasma
description: |
    Addons for KDE Plasma.
builddeps  :
    - pkgconfig(libKActivities)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - extra-cmake-modules
    - karchive-devel
    - kcmutils-devel
    - kdeclarative-devel
    - kholidays-devel
    - knewstuff-devel
    - knotifications-devel
    - krunner-devel
    - kunitconversion-devel
    - kross-devel
    - kwindowsystem-devel
    - libksysguard-devel
    - plasma-workspace-devel
    - purpose-devel
    - sonnet-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-diskquota.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache

    # Remove locale data for removed applet
    rm $installdir/usr/share/locale/*/LC_MESSAGES/plasma_applet_org.kde.plasma.diskquota.mo
